name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

sort-direction: ascending

categories:
  - title: '🚀 Features'
    when:
      labels:
        - 'feature'
        - 'enhancement'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'bug'
  - title: '📦 Dependencies'
    when:
      labels:
        - 'dependencies'
  - title: '🧰 Maintenance'
    when:
      labels:
        - 'chore'

autolabeler:
  - label: 'feature'
    branch:
      - '/^feat\/.+/'
      - '/^feature\/.+/'
  - label: 'bug'
    branch:
      - '/^fix\/.+/'
      - '/^bug\/.+/'
  - label: 'chore'
    branch:
      - '/^chore\/.+/'
  - label: 'dependencies'
    branch:
      - '/^deps\/.+/'
      - '/^dependencies\/.+/'
      - '/^dependabot\/.+/'
      - '/^renovate\/.+/'
    files:
      - 'package-lock.json'
      - '**/package-lock.json'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
